"""Import the user-supplied Red Book PDF. Requires pymupdf.
Usage: python3 tools/import_redbook.py /path/to/book.pdf
"""
import json, re, sys, shutil
from pathlib import Path
import pymupdf

ROOT = Path(__file__).resolve().parents[1]
doc = pymupdf.open(sys.argv[1])
heading = re.compile(r'^(\d+)\.\s*([А-ЯӨҮЁ][А-ЯӨҮЁ \-–\[\]]+)$')
records = []
current = None
for page_index in range(221, 397):
    events = []
    for block in doc[page_index].get_text('dict')['blocks']:
        if block['type'] == 1:
            events.append((block['bbox'][1], 'image', block))
        else:
            for line in block['lines']:
                text = ''.join(span['text'] for span in line['spans']).strip()
                if text:
                    events.append((line['bbox'][1], 'text', text))
    for _, kind, value in sorted(events, key=lambda e: e[0]):
        if kind == 'text' and (match := heading.fullmatch(value)):
            no = int(match[1])
            assert no == len(records) + 1, (page_index + 1, no)
            current = {'no': no, 'mn': match[2], 'lines': [], 'images': [], 'pages': []}
            records.append(current)
        elif current:
            if kind == 'text':
                current['lines'].append(value)
            else:
                path = f'assets/plants/{current["no"]:03d}-{len(current["images"])+1}.{value["ext"]}'
                (ROOT / path).write_bytes(value['image'])
                current['images'].append(path)
        if current and page_index + 1 not in current['pages']:
            current['pages'].append(page_index + 1)
assert [r['no'] for r in records] == list(range(1, 136))

regions = ['Хөвсгөл', 'Хэнтий', 'Хангай', 'Монгол Дагуур', 'Хянган', 'Ховд', 'Монгол Алтай', 'Дундад Халх', 'Дорнод Монгол', 'Их нууруудын хотгор', 'Олон нуурын хөндий', 'Говь Алтай', 'Зүүнгарын говь', 'Зүүн говь', 'Алашаа говь']
region_patterns = ['хөвсгөл', 'хэнтий', 'хангай', 'монгол дагуур', 'хянган', 'ховд', 'монгол алтай', 'дундад халх', 'дорнод монгол', 'их нуурууд', 'олон нуур', 'говь алтай', 'зүүнгар', 'зүүн говь|дорноговь', 'алашаа']
habitats = {'Ой, тайга':r'ойн|ойд|ойт|тайг|төгөл', 'Хад, асга, чулуурхаг':r'хад|асга|чулуу|хайрга', 'Нуга, намаг':r'нуг|намаг', 'Хээр':r'хээр', 'Цөл, говь, элс':r'цөл|гов|элс', 'Нуур, гол, ус':r'нуур|гол|горхи|усан|усны'}
labels = re.compile(r'(Статус|[ТT]аних шинж|Шинж таних|Тархац(?:,?\s*ургах орчин)?|Үржил|Нөөц,?\s*хомсдох шал(?:т)?гаан|Хамгаалаа?хаар авсан арга хэмжээ|Хамгаалсан байдал|Хамгаалах арга хэмжээ|Эх зохи?ол,?\s*мэдээ)\s*:')
for r in records:
    lines = r.pop('lines')
    r['fullText'] = '\n'.join(lines)
    text = re.sub(r'\s+', ' ', r['fullText']).strip()
    matches = list(labels.finditer(text))
    r['sections'] = [{'title':m[1], 'text':text[m.end():matches[i+1].start() if i+1<len(matches) else len(text)].strip()} for i,m in enumerate(matches)]
    def section(prefix):
        return next((s['text'] for s in r['sections'] if s['title'].startswith(prefix)), '')
    family_line = next(l for l in lines if l.startswith('Овог'))
    family = re.search(r'[A-Z][a-z]+aceae', family_line)
    r['fam'] = family[0] if family else family_line
    r['famMN'] = re.split(r'\s*[–—-]\s*', re.sub(r'^Овог\s*[.:]?\s*','',family_line))[0]
    r['laFull'] = ' '.join(lines[:lines.index(family_line)])
    r['division'] = next((v for v in ['Pteridophyta','Pinophytina','Magnoliophytina','Magnoliophyta'] if v in r['laFull']), '')
    r['laFull'] = r['laFull'].replace(r['division'], '').strip() if r['division'] else r['laFull']
    r['la'] = ' '.join(r['laFull'].split()[:2])
    r['status'] = section('Статус')
    r['cat'] = 'Нэн ховор' if re.search('нэн ховор',r['status'],re.I) else 'Ховор' if re.search('[хx]овор',r['status'],re.I) else 'Тодорхойгүй'
    r['tags'] = [v for v in ['унаган','завсрын унаган','үлдвэр'] if v in r['status'].lower()]
    r['habitat'] = section('Тархац')
    local = re.split(r'Монголд\s*:',r['habitat'],maxsplit=1)[-1].lower().replace('-',' ')
    r['reg'] = [name for name,pat in zip(regions,region_patterns) if re.search(pat,local)]
    r['hab'] = [name for name,pat in habitats.items() if re.search(pat,local)]
    for key,pattern in [('iw',r'олон улсын хэмжээнд\s*[“\"]([^”\"]+)[”\"]'),('ir',r'бүс нутгийн хэмжээнд\s*[“\"]([^”\"]+)[”\"]')]:
        m=re.search(pattern,r['status']);r[key]=m[1] if m else ''
    r['src'] = 'Улаан данс' if r['iw'] or r['ir'] else 'Улаан ном'
    r['col'] = [];r['mo'] = None
    assert r['images'], r['no']
    assert r['sections'] and r['status'] and r['habitat'], (r['no'],r['sections'])
    r['img'] = r['images'][0]
    r['source'] = 'sources/mongolian-red-book.pdf'
(ROOT/'data/plants.json').write_text(json.dumps(records,ensure_ascii=False,indent=2)+'\n')
(ROOT/'data/plants.js').write_text('/* Generated by tools/import_redbook.py from the supplied PDF. */\nconst D = '+json.dumps(records,ensure_ascii=False,indent=2)+';\n')
shutil.copyfile(sys.argv[1],ROOT/'sources/mongolian-red-book.pdf')
print('Imported',len(records),'plants;',sum(len(r['images']) for r in records),'images.')
print('Section counts:', {n:sum(len(r['sections'])==n for r in records) for n in set(len(r['sections']) for r in records)})
print('Missing divisions:',[r['no'] for r in records if not r['division']])
